import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/cvphoto.jpeg";
import comingsoon from "../public/comingsoon.jpg";
import { useState } from "react";
import Typical from "react-typical";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Federico Iglesia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="  min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="text-xl font-burtons">Federico</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl "
                />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r border border-cyan-500 from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 transition duration-500 hover:to-white hover:from-white hover:text-teal-500 hover:border hover:border-teal-500"
                  target="_blank"
                  href="resume.pdf"
                  rel="noopener noreferrer"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Federico Iglesia
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Full Stack Web Developer
            </h3>
            <div className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white">
              9 years until i finally found what what really motivates me:
              <Typical
                className="text-teal-600 dark:text-white"
                steps={[
                  "Coding",
                  3000,
                  "Web Development",
                  3000,
                  "Software",
                  3000,
                  "Problem Solving",
                  3000,
                ]}
                wrapper="p"
                loop={Infinity}
              />
            </div>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a
              href="https://www.linkedin.com/in/federicojiglesia/"
              target="_blank"
              rel="noreferrer"
            >
              <AiFillLinkedin className="dark:text-white social hover:text-blue-500 dark:hover:text-teal-300" />
            </a>
            <a
              href="https://twitter.com/iglesfe1"
              target="_blank"
              rel="noreferrer"
            >
              <AiFillTwitterCircle className="dark:text-white social hover:text-sky-400 dark:hover:text-teal-300" />
            </a>
            <a
              href="https://github.com/FedericoIglesia"
              target="_blank"
              rel="noreferrer"
            >
              <AiFillGithub className="dark:text-white social hover:text-gray-400 dark:hover:text-teal-300" />
            </a>
          </div>
          <div className="mx-auto border-solid border-4 border-teal-500 rounded-full w-80 h-80 overflow-hidden mt-20 md:h-96 md:w-96 dark:bg-white">
            <Image
              src={deved}
              className=" rounded-full object-fill w-80 h-85 mx-auto  border-teal-500"
            />
          </div>
        </section>
        {/* <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">My Tech Stack</h3>
            <p className="text-md py-2 leading-8 text-gray-800  dark:text-white">
              lorem20
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image
                className="mx-auto"
                src={design}
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2  dark:text-white">
                Lorem
              </h3>
              <p className="py-2  dark:text-white">bla bal bla </p>
              <h4 className="py-4 text-teal-600">Tools</h4>
              <p className="text-gray-800 py-1  dark:text-white">React</p>
              <p className="text-gray-800 py-1  dark:text-white">Figma</p>
              <p className="text-gray-800 py-1  dark:text-white">Figma</p>
              <p className="text-gray-800 py-1  dark:text-white">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image
                className="mx-auto"
                src={consulting}
                width={100}
                height={100}
              />
              <h3 className="text-lg font-medium pt-8 pb-2  dark:text-white">
                Lorem
              </h3>
              <p className="py-2  dark:text-white">bla bal bla </p>
              <h4 className="py-4 text-teal-600">Tools</h4>
              <p className="text-gray-800 py-1  dark:text-white">React</p>
              <p className="text-gray-800 py-1  dark:text-white">Figma</p>
              <p className="text-gray-800 py-1  dark:text-white">Figma</p>
              <p className="text-gray-800 py-1  dark:text-white">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image className="mx-auto" src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  dark:text-white">
                Lorem
              </h3>
              <p className="py-2  dark:text-white">bla bal bla </p>
              <h4 className="py-4 text-teal-600">Tools</h4>
              <p className="text-gray-800 py-1  dark:text-white">React</p>
              <p className="text-gray-800 py-1  dark:text-white">Figma</p>
              <p className="text-gray-800 py-1  dark:text-white">Figma</p>
              <p className="text-gray-800 py-1  dark:text-white">Figma</p>
            </div>
          </div>
        </section> */}
        <section>
          <div className="mt-15 ">
            <h3 className="text-3xl py-10 text-center  dark:text-white">
              My Portfolio
            </h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <a
                href="https://github.com/FedericoIglesia/TheFoodPlace"
                target="_blank"
                rel="noreferrer"
              >
                <img
                  src="https://user-images.githubusercontent.com/85205823/189451007-7730ea3e-30aa-4c52-8869-708b42eb5985.gif"
                  className="rounded-lg object-cover"
                ></img>
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a
                href="https://github.com/FedericoIglesia/Athens_front"
                target="_blank"
                rel="noreferrer"
              >
                <img
                  src="https://user-images.githubusercontent.com/85205823/192325244-1e46ba81-e6da-4f26-b3f0-ff3fd068a8eb.gif"
                  className="rounded-lg object-cover"
                ></img>
              </a>
              {/* <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              /> */}
            </div>
            <div className="basis-1/3 flex-1">
              <a
                href="https://github.com/FedericoIglesia/42iChallenge"
                target="_blank"
                rel="noreferrer"
              >
                <img
                  src="https://user-images.githubusercontent.com/85205823/192326604-e28f6f01-cc52-4611-b3cf-4793de6b5a9c.gif"
                  className="rounded-lg object-cover"
                ></img>
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={comingsoon}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
        <div style={{ color: "gray", fontSize: "5px" }}>
          <a href="https://www.freepik.es/vector-gratis/resumen-proximamente-diseno-fondo-estilo-semitono_10016647.htm#query=coming%20soon&position=3&from_view=keyword">
            Imagen de starline
          </a>{" "}
          en Freepik
        </div>
      </main>
    </div>
  );
}
